### ISSUE TITLE
Nuova liberatoria

### ISSUE THREAD

**Issue by stepanz70** [CoderDojoMilano/piccolevariabili.it#10]
Ciao, ho reso compilabile il PDF della liberatoria.
E' possibile sostituire il file attuale con questo?
Grazie.
[Liberatoria_utilizzo_materiale_AV_2015.pdf](https://github.com/CoderDojoMilano/piccolevariabili.it/files/530405/Liberatoria_utilizzo_materiale_AV_2015.pdf)

**Comment by lordkada** [comment]
Ti ho scritto su slack per maggiori dettagli :-)
