### ISSUE TITLE
Aggiornamento coordinate bancarie

### ISSUE THREAD

**Issue by stepanz70** [CoderDojoMilano/piccolevariabili.it#12]
Questo è l'Iban del nuovo conto corrente

IT77Y0200820100000104606009

Banca UniCredit

Da sostituire nella pagine con le istruzioni per il rinnovo della quota associativa e delle donazioni.
Per PayPal non cambia niente.

**Comment by lordkada** [comment]
Stavo per aggiornare, ma mi sembra che @giampiero7 abbia già fatto... :-)
Chiudo il ticket

**Comment by stepanz70** [comment]
Ciao, ne ho aperta anche una per CoderDojo (evento Discovery).
Grazie.

Il 06 feb 2017 9:55 AM, "Carlo Alberto Degli Atti" <notifications@github.com>
ha scritto:

**Comment by giampiero7** [comment]
Scusate.. non avevo visto l'issue :)

**Comment by lordkada** [comment]
@giampiero7 no prob.. ho fatto io ;-)
