### ISSUE TITLE
Add field "Codice Fiscale / P.IVA" for PayPal donations

### ISSUE THREAD

**Issue by giampiero7** [CoderDojoMilano/piccolevariabili.it#3]

**Comment by lordkada** [comment]
Con la pr #6 chiudiamo questo ticket?

**Comment by giampiero7** [comment]
Lo lascio aperto per il fix al controllo dell'inserimento obbligatorio?

**Comment by lordkada** [comment]
Per chiarezza aprirei un altro ticket :-)
